(function () {
  'use strict';
  const root = document.documentElement;
  const storage = { get(key, fallback = null) { try { return window.localStorage.getItem(key) || fallback; } catch (error) { return fallback; } }, set(key, value) { try { window.localStorage.setItem(key, value); } catch (error) {} } };
  root.classList.add('js-ready');
  const fxStatus = document.querySelector('#fx-status');
  if (fxStatus) { fxStatus.classList.add('is-ready'); fxStatus.querySelector('span').textContent = 'NEXULVI FX ONLINE'; }
  window.addEventListener('error', (event) => { if (fxStatus) fxStatus.querySelector('span').textContent = `FX ERROR // ${event.message || 'SCRIPT'}`; });
  const themeToggle = document.querySelector('#theme-toggle');
  const languageSelect = document.querySelector('#language-select');
  const menuToggle = document.querySelector('#menu-toggle');
  const mobileNav = document.querySelector('#mobile-nav');
  const translations = {
    pt: { skip:'Pular para o conteúdo', navSolutions:'Soluções', navManifesto:'Manifesto', navSupport:'Apoie', eyebrow:'ESTÚDIO DIGITAL INDEPENDENTE', heroLineOne:'Conectando', heroLineTwo:'ideias ao futuro.', heroDescription:'A Nexulvi cria aplicativos e experiências digitais que transformam possibilidades em algo real, simples e útil.', explore:'Explorar soluções', discover:'Descobrir a Nexulvi', manifestoEyebrow:'NOSSO MANIFESTO', manifestoTitle:'O próximo passo começa<br><em>com uma ideia.</em>', manifestoCopy:'Nexulvi combina curiosidade, design e tecnologia para criar ferramentas que acompanham a vida real. Não criamos por criar. Cada solução nasce para aproximar pessoas de possibilidades que antes pareciam distantes.', statOne:'visão conectada', statTwo:'possibilidades', statThree:'em movimento', solutionsEyebrow:'O QUE ESTAMOS CRIANDO', solutionsTitle:'Soluções para<br><em>o agora.</em>', solutionsNote:'Uma coleção crescente de aplicativos pensados para tornar o digital mais humano, acessível e interessante.', comingSoon:'EM BREVE', future:'FUTURO', categoryOne:'PRODUTIVIDADE', categoryTwo:'EXPERIÊNCIAS DIGITAIS', categoryThree:'LABORATÓRIO', appOne:'Nova solução em desenvolvimento', appOneDescription:'Uma nova forma de organizar suas ideias e transformar intenção em ação.', appTwo:'Próxima conexão', appTwoDescription:'Tecnologia discreta para ajudar você a viver melhor o seu tempo.', appThree:'Ideias em movimento', appThreeDescription:'Experimentos que podem se tornar a próxima grande solução da Nexulvi.', followLaunch:'Acompanhar lançamento', learnMore:'Saiba mais', followJourney:'Seguir a jornada', signalEyebrow:'NOSSO SINAL', signalTitle:'Feito para quem<br><em>pensa adiante.</em>', signalCopy:'A tecnologia muda rápido. Nossa curiosidade, mais rápido ainda. Acompanhe o que vem a seguir.', supportEyebrow:'FAÇA PARTE', supportTitle:'Ajude a próxima<br><em>ideia a decolar.</em>', supportCopy:'A Nexulvi está apenas começando. Seu apoio ajuda a manter os projetos independentes vivos, acessíveis e em constante evolução.', supportButton:'Quero apoiar o projeto', qrLabel:'QR CODE // APOIE', qrNote:'Link de apoio em breve', footerTagline:'Conectando ideias ao futuro.', backTop:'Voltar ao topo ↑', rights:'Todos os direitos reservados.', status:'Sistemas online', madeWith:'Feito com curiosidade e código.' },
    en: { skip:'Skip to content', navSolutions:'Solutions', navManifesto:'Manifesto', navSupport:'Support', eyebrow:'INDEPENDENT DIGITAL STUDIO', heroLineOne:'Connecting', heroLineTwo:'ideas to the future.', heroDescription:'Nexulvi creates apps and digital experiences that turn possibilities into something real, simple and useful.', explore:'Explore solutions', discover:'Discover Nexulvi', manifestoEyebrow:'OUR MANIFESTO', manifestoTitle:'The next step starts<br><em>with an idea.</em>', manifestoCopy:'Nexulvi combines curiosity, design and technology to create tools that fit real life. We do not create just to create. Every solution brings people closer to possibilities that once felt distant.', statOne:'connected vision', statTwo:'possibilities', statThree:'in motion', solutionsEyebrow:'WHAT WE ARE CREATING', solutionsTitle:'Solutions for<br><em>right now.</em>', solutionsNote:'A growing collection of apps designed to make digital life more human, accessible and interesting.', comingSoon:'COMING SOON', future:'FUTURE', categoryOne:'PRODUCTIVITY', categoryTwo:'DIGITAL EXPERIENCES', categoryThree:'LABORATORY', appOne:'New solution in development', appOneDescription:'A new way to organize your ideas and turn intention into action.', appTwo:'The next connection', appTwoDescription:'Quiet technology to help you make better use of your time.', appThree:'Ideas in motion', appThreeDescription:'Experiments that may become Nexulvi’s next great solution.', followLaunch:'Follow the launch', learnMore:'Learn more', followJourney:'Follow the journey', signalEyebrow:'OUR SIGNAL', signalTitle:'Made for those<br><em>who think ahead.</em>', signalCopy:'Technology changes fast. Our curiosity changes faster. Follow what comes next.', supportEyebrow:'BE PART OF IT', supportTitle:'Help the next<br><em>idea take off.</em>', supportCopy:'Nexulvi is just getting started. Your support helps keep independent projects alive, accessible and evolving.', supportButton:'Support the project', qrLabel:'QR CODE // SUPPORT', qrNote:'Support link coming soon', footerTagline:'Connecting ideas to the future.', backTop:'Back to top ↑', rights:'All rights reserved.', status:'Systems online', madeWith:'Made with curiosity and code.' },
    es: { skip:'Saltar al contenido', navSolutions:'Soluciones', navManifesto:'Manifiesto', navSupport:'Apoyar', eyebrow:'ESTUDIO DIGITAL INDEPENDIENTE', heroLineOne:'Conectando', heroLineTwo:'ideas al futuro.', heroDescription:'Nexulvi crea aplicaciones y experiencias digitales que convierten posibilidades en algo real, simple y útil.', explore:'Explorar soluciones', discover:'Descubrir Nexulvi', manifestoEyebrow:'NUESTRO MANIFIESTO', manifestoTitle:'El siguiente paso empieza<br><em>con una idea.</em>', manifestoCopy:'Nexulvi combina curiosidad, diseño y tecnología para crear herramientas que acompañan la vida real.', statOne:'visión conectada', statTwo:'posibilidades', statThree:'en movimiento', solutionsEyebrow:'LO QUE ESTAMOS CREANDO', solutionsTitle:'Soluciones para<br><em>el presente.</em>', solutionsNote:'Una colección creciente de aplicaciones pensadas para hacer lo digital más humano, accesible e interesante.', comingSoon:'PRÓXIMAMENTE', future:'FUTURO', categoryOne:'PRODUCTIVIDAD', categoryTwo:'EXPERIENCIAS DIGITALES', categoryThree:'LABORATORIO', appOne:'Nueva solución en desarrollo', appOneDescription:'Una nueva forma de organizar tus ideas y convertir la intención en acción.', appTwo:'La próxima conexión', appTwoDescription:'Tecnología discreta para ayudarte a aprovechar mejor tu tiempo.', appThree:'Ideas en movimiento', appThreeDescription:'Experimentos que pueden convertirse en la próxima solución de Nexulvi.', followLaunch:'Seguir lanzamiento', learnMore:'Saber más', followJourney:'Seguir el camino', signalEyebrow:'NUESTRA SEÑAL', signalTitle:'Hecho para quienes<br><em>piensan adelante.</em>', signalCopy:'La tecnología cambia rápido. Nuestra curiosidad, aún más rápido.', supportEyebrow:'SÉ PARTE', supportTitle:'Ayuda a que la próxima<br><em>idea despegue.</em>', supportCopy:'Nexulvi acaba de comenzar. Tu apoyo ayuda a mantener proyectos independientes vivos y en evolución.', supportButton:'Apoyar el proyecto', qrLabel:'CÓDIGO QR // APOYAR', qrNote:'Enlace de apoyo próximamente', footerTagline:'Conectando ideas al futuro.', backTop:'Volver arriba ↑', rights:'Todos los derechos reservados.', status:'Sistemas online', madeWith:'Hecho con curiosidad y código.' },
    fr: { skip:'Aller au contenu', navSolutions:'Solutions', navManifesto:'Manifeste', navSupport:'Soutenir', eyebrow:'STUDIO NUMÉRIQUE INDÉPENDANT', heroLineOne:'Connecter', heroLineTwo:'les idées au futur.', heroDescription:'Nexulvi crée des applications et expériences numériques qui transforment les possibilités en quelque chose de réel, simple et utile.', explore:'Explorer les solutions', discover:'Découvrir Nexulvi', manifestoEyebrow:'NOTRE MANIFESTE', manifestoTitle:'La prochaine étape commence<br><em>par une idée.</em>', manifestoCopy:'Nexulvi associe curiosité, design et technologie pour créer des outils adaptés à la vie réelle.', statOne:'vision connectée', statTwo:'possibilités', statThree:'en mouvement', solutionsEyebrow:'CE QUE NOUS CRÉONS', solutionsTitle:'Des solutions pour<br><em>aujourd’hui.</em>', solutionsNote:'Une collection croissante d’applications conçues pour rendre le numérique plus humain, accessible et intéressant.', comingSoon:'BIENTÔT', future:'FUTUR', categoryOne:'PRODUCTIVITÉ', categoryTwo:'EXPÉRIENCES NUMÉRIQUES', categoryThree:'LABORATOIRE', appOne:'Nouvelle solution en développement', appOneDescription:'Une nouvelle façon d’organiser vos idées et de transformer l’intention en action.', appTwo:'La prochaine connexion', appTwoDescription:'Une technologie discrète pour mieux profiter de votre temps.', appThree:'Des idées en mouvement', appThreeDescription:'Des expériences qui pourraient devenir la prochaine solution Nexulvi.', followLaunch:'Suivre le lancement', learnMore:'En savoir plus', followJourney:'Suivre le parcours', signalEyebrow:'NOTRE SIGNAL', signalTitle:'Pensé pour ceux<br><em>qui vont de l’avant.</em>', signalCopy:'La technologie évolue vite. Notre curiosité encore plus vite.', supportEyebrow:'REJOIGNEZ-NOUS', supportTitle:'Aidez la prochaine<br><em>idée à décoller.</em>', supportCopy:'Nexulvi ne fait que commencer. Votre soutien aide les projets indépendants à rester vivants et accessibles.', supportButton:'Soutenir le projet', qrLabel:'CODE QR // SOUTENIR', qrNote:'Lien bientôt disponible', footerTagline:'Connecter les idées au futur.', backTop:'Retour en haut ↑', rights:'Tous droits réservés.', status:'Systèmes en ligne', madeWith:'Fait avec curiosité et du code.' },
    de: { skip:'Zum Inhalt springen', navSolutions:'Lösungen', navManifesto:'Manifest', navSupport:'Unterstützen', eyebrow:'UNABHÄNGIGES DIGITALES STUDIO', heroLineOne:'Ideen', heroLineTwo:'mit der Zukunft verbinden.', heroDescription:'Nexulvi entwickelt Apps und digitale Erlebnisse, die Möglichkeiten in etwas Reales, Einfaches und Nützliches verwandeln.', explore:'Lösungen entdecken', discover:'Nexulvi entdecken', manifestoEyebrow:'UNSER MANIFEST', manifestoTitle:'Der nächste Schritt beginnt<br><em>mit einer Idee.</em>', manifestoCopy:'Nexulvi verbindet Neugier, Design und Technologie, um Werkzeuge für das echte Leben zu schaffen.', statOne:'verbundene Vision', statTwo:'Möglichkeiten', statThree:'in Bewegung', solutionsEyebrow:'WAS WIR ENTWICKELN', solutionsTitle:'Lösungen für<br><em>das Jetzt.</em>', solutionsNote:'Eine wachsende Sammlung von Apps, die das Digitale menschlicher, zugänglicher und spannender machen.', comingSoon:'BALD VERFÜGBAR', future:'ZUKUNFT', categoryOne:'PRODUKTIVITÄT', categoryTwo:'DIGITALE ERLEBNISSE', categoryThree:'LABOR', appOne:'Neue Lösung in Entwicklung', appOneDescription:'Eine neue Art, Ideen zu organisieren und Absichten in Taten zu verwandeln.', appTwo:'Die nächste Verbindung', appTwoDescription:'Unaufdringliche Technologie für eine bessere Nutzung deiner Zeit.', appThree:'Ideen in Bewegung', appThreeDescription:'Experimente, die Nexulvis nächste große Lösung werden können.', followLaunch:'Start verfolgen', learnMore:'Mehr erfahren', followJourney:'Reise verfolgen', signalEyebrow:'UNSER SIGNAL', signalTitle:'Für alle, die<br><em>weiter denken.</em>', signalCopy:'Technologie verändert sich schnell. Unsere Neugier noch schneller.', supportEyebrow:'SEI DABEI', supportTitle:'Hilf der nächsten<br><em>Idee beim Start.</em>', supportCopy:'Nexulvi steht erst am Anfang. Deine Unterstützung hält unabhängige Projekte lebendig und in Bewegung.', supportButton:'Projekt unterstützen', qrLabel:'QR-CODE // SUPPORT', qrNote:'Support-Link folgt bald', footerTagline:'Ideen mit der Zukunft verbinden.', backTop:'Nach oben ↑', rights:'Alle Rechte vorbehalten.', status:'Systeme online', madeWith:'Mit Neugier und Code gemacht.' }
  };
  function setLanguage(lang) { const dict = translations[lang] || translations.pt; document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang; document.querySelectorAll('[data-i18n]').forEach((el) => { if (dict[el.dataset.i18n]) el.innerHTML = dict[el.dataset.i18n]; }); storage.set('nexulvi-language', lang); }
  function setTheme(theme) { root.dataset.theme = theme; themeToggle.setAttribute('aria-pressed', theme === 'light'); themeToggle.setAttribute('aria-label', theme === 'light' ? 'Ativar modo escuro' : 'Ativar modo claro'); const themeColor = document.querySelector('meta[name="theme-color"]'); if (themeColor) themeColor.setAttribute('content', theme === 'light' ? '#f3f8f7' : '#071018'); storage.set('nexulvi-theme', theme); }
  const savedTheme = storage.get('nexulvi-theme') || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark');
  const savedLanguage = storage.get('nexulvi-language') || 'pt'; languageSelect.value = savedLanguage; setLanguage(savedLanguage); setTheme(savedTheme);
  function runViewTransition(update) { if (document.startViewTransition && !root.classList.contains('reduce-motion')) document.startViewTransition(update); else update(); }
  const motionToggle = document.querySelector('#motion-toggle');
  const stereoToggle = document.querySelector('#stereo-toggle');
  const hero = document.querySelector('.hero');
  const systemReducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
  function setStereo(enabled) { hero.classList.toggle('stereo-mode', enabled); stereoToggle.setAttribute('aria-pressed', String(enabled)); stereoToggle.setAttribute('aria-label', enabled ? 'Desativar modo estéreo' : 'Ativar modo estéreo'); if (fxStatus) fxStatus.querySelector('span').textContent = enabled ? 'NEXULVI FX // S3D ACTIVE' : 'NEXULVI FX ONLINE'; storage.set('nexulvi-stereo-v3', enabled ? 'on' : 'off'); }
  function setMotionReduction(reduced) { root.classList.toggle('reduce-motion', reduced); motionToggle.setAttribute('aria-pressed', String(reduced)); motionToggle.setAttribute('aria-label', reduced ? 'Ativar animações' : 'Reduzir animações'); if (!systemReducedMotion) storage.set('nexulvi-motion-v3', reduced ? 'reduced' : 'full'); }
  setMotionReduction(storage.get('nexulvi-motion-v3') === 'reduced' || systemReducedMotion);
  motionToggle.addEventListener('click', () => setMotionReduction(!root.classList.contains('reduce-motion')));
  const stereoDefault = storage.get('nexulvi-stereo-v3', 'on') !== 'off';
  setStereo(stereoDefault);
  stereoToggle.addEventListener('click', () => { if (!root.classList.contains('reduce-motion')) setStereo(!hero.classList.contains('stereo-mode')); });
  themeToggle.addEventListener('click', () => runViewTransition(() => setTheme(root.dataset.theme === 'light' ? 'dark' : 'light')));
  languageSelect.addEventListener('change', (event) => runViewTransition(() => setLanguage(event.target.value)));
  menuToggle.addEventListener('click', () => { const isOpen = mobileNav.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(isOpen)); });
  mobileNav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { mobileNav.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); }));
  const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); if (entry.target.classList.contains('scroll-scene')) entry.target.classList.add('scene-live'); observer.unobserve(entry.target); } }), { threshold: .12 });
  document.querySelectorAll('.reveal').forEach((element) => observer.observe(element));
  const glow = document.querySelector('.cursor-glow');
  const progress = document.querySelector('.scroll-progress span');
  const header = document.querySelector('.site-header');
  const loader = document.querySelector('#site-loader');
  const loaderPercent = document.querySelector('.loader-percent');
  let loaderValue = 0;
  const loaderTimer = window.setInterval(() => { loaderValue = Math.min(loaderValue + Math.ceil(Math.random() * 17), 100); loaderPercent.textContent = `${String(loaderValue).padStart(2, '0')}%`; if (loaderValue >= 100) { window.clearInterval(loaderTimer); window.setTimeout(() => loader.classList.add('is-hidden'), 180); } }, 90);
  let ticking = false;
  function updateScrollEffects() {
    const maxScroll = document.documentElement.scrollHeight - window.innerHeight;
    const amount = maxScroll > 0 ? Math.min(window.scrollY / maxScroll, 1) : 0;
    root.style.setProperty('--scroll-progress', amount.toFixed(3));
    root.style.setProperty('--scroll-scale', (0.7 + amount * 0.5).toFixed(3));
    root.style.setProperty('--hero-parallax', Math.min(window.scrollY, 260).toFixed(1));
    root.style.setProperty('--signal-angle', `${(window.scrollY * .035).toFixed(1)}deg`);
    document.body.classList.toggle('scene-charging', window.scrollY > 24);
    progress.style.width = `${amount * 100}%`;
    header.classList.toggle('scrolled', window.scrollY > 18);
    ticking = false;
  }
  window.addEventListener('scroll', () => { if (!ticking) { window.requestAnimationFrame(updateScrollEffects); ticking = true; } }, { passive: true });
  updateScrollEffects();
  const canHover = matchMedia('(hover: hover) and (pointer: fine)').matches;
  if (canHover) {
    const cursorSystem = document.querySelector('.cursor-system');
    const cursorCore = document.querySelector('.cursor-core');
    const cursorRing = document.querySelector('.cursor-ring');
    const cursorLabel = document.querySelector('.cursor-label');
    let pointerX = window.innerWidth / 2; let pointerY = window.innerHeight / 2; let ringX = pointerX; let ringY = pointerY;
    cursorSystem.classList.add('is-active');
    const trail = document.createElement('div');
    trail.className = 'cursor-trail';
    const trailDots = Array.from({ length: 9 }, () => { const dot = document.createElement('i'); trail.appendChild(dot); return dot; });
    const trailPoints = trailDots.map(() => ({ x: pointerX, y: pointerY }));
    document.body.appendChild(trail);
    function moveCursor() {
      ringX += (pointerX - ringX) * .16; ringY += (pointerY - ringY) * .16;
      cursorCore.style.left = `${pointerX}px`; cursorCore.style.top = `${pointerY}px`; cursorRing.style.left = `${ringX}px`; cursorRing.style.top = `${ringY}px`; cursorLabel.style.left = `${ringX}px`; cursorLabel.style.top = `${ringY}px`;
      trailPoints.forEach((point, index) => { const target = index === 0 ? { x: pointerX, y: pointerY } : trailPoints[index - 1]; point.x += (target.x - point.x) * (.25 - index * .015); point.y += (target.y - point.y) * (.25 - index * .015); trailDots[index].style.left = `${point.x}px`; trailDots[index].style.top = `${point.y}px`; trailDots[index].style.opacity = `${Math.max(0, .48 - index * .045)}`; });
      window.requestAnimationFrame(moveCursor);
    }
    moveCursor();
    window.addEventListener('pointermove', (event) => { pointerX = event.clientX; pointerY = event.clientY; glow.style.left = `${event.clientX}px`; glow.style.top = `${event.clientY}px`; }, { passive: true });
    document.querySelectorAll('a, button, select, .app-card, [data-cursor]').forEach((element) => { element.addEventListener('pointerenter', () => { cursorSystem.classList.add('is-hover'); cursorLabel.textContent = element.dataset.cursor || (element.classList.contains('app-card') ? 'VIEW' : 'OPEN'); }); element.addEventListener('pointerleave', () => cursorSystem.classList.remove('is-hover')); });
    document.querySelectorAll('.button, .card-link, .text-link').forEach((element) => {
       element.addEventListener('pointermove', (event) => { const rect = element.getBoundingClientRect(); const localX = event.clientX - rect.left; const localY = event.clientY - rect.top; element.style.setProperty('--pointer-x', `${localX}px`); element.style.setProperty('--pointer-y', `${localY}px`); if (element.classList.contains('button')) { element.style.setProperty('--mag-x', `${((localX / rect.width) - .5) * 8}px`); element.style.setProperty('--mag-y', `${((localY / rect.height) - .5) * 5}px`); } });
      element.addEventListener('pointerenter', () => glow.classList.add('cursor-hover'));
       element.addEventListener('pointerleave', () => { glow.classList.remove('cursor-hover'); element.style.setProperty('--mag-x', '0px'); element.style.setProperty('--mag-y', '0px'); });
      element.addEventListener('click', (event) => { const rect = element.getBoundingClientRect(); const ripple = document.createElement('span'); ripple.className = 'ripple'; ripple.setAttribute('aria-hidden', 'true'); ripple.style.left = `${event.clientX - rect.left}px`; ripple.style.top = `${event.clientY - rect.top}px`; element.appendChild(ripple); ripple.addEventListener('animationend', () => ripple.remove(), { once: true }); });
    });
     document.querySelectorAll('.app-card').forEach((card) => {
       card.addEventListener('pointermove', (event) => { const rect = card.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width; const y = (event.clientY - rect.top) / rect.height; card.style.setProperty('--tilt-y', `${((x - .5) * 7).toFixed(2)}deg`); card.style.setProperty('--tilt-x', `${((.5 - y) * 7).toFixed(2)}deg`); card.style.setProperty('--shine-x', `${(x * 100).toFixed(1)}%`); card.style.setProperty('--shine-y', `${(y * 100).toFixed(1)}%`); });
       card.addEventListener('pointerleave', () => { card.style.setProperty('--tilt-x', '0deg'); card.style.setProperty('--tilt-y', '0deg'); });
     });
     const interactiveHero = document.querySelector('.hero-visual');
     if (interactiveHero) {
       interactiveHero.addEventListener('pointermove', (event) => { const rect = interactiveHero.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width - .5; const y = (event.clientY - rect.top) / rect.height - .5; interactiveHero.style.setProperty('--hero-tilt-y', `${(x * 8).toFixed(2)}deg`); interactiveHero.style.setProperty('--hero-tilt-x', `${(-y * 6).toFixed(2)}deg`); });
       interactiveHero.addEventListener('pointerleave', () => { interactiveHero.style.setProperty('--hero-tilt-x', '0deg'); interactiveHero.style.setProperty('--hero-tilt-y', '0deg'); });
     }
   }
  const sections = [...document.querySelectorAll('main section[id]')];
  const navLinks = [...document.querySelectorAll('.desktop-nav a, .mobile-nav a')];
  const sectionObserver = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) navLinks.forEach((link) => link.classList.toggle('active', link.getAttribute('href') === `#${entry.target.id}`)); }), { rootMargin: '-30% 0px -55% 0px' });
  sections.forEach((section) => sectionObserver.observe(section));
  const scenes = [...document.querySelectorAll('.scroll-scene')];
  function updateScenes() { scenes.forEach((scene) => { const rect = scene.getBoundingClientRect(); const span = window.innerHeight + rect.height; const progress = Math.max(0, Math.min(1, (window.innerHeight - rect.top) / span)); scene.style.setProperty('--scene-progress', progress.toFixed(3)); scene.style.setProperty('--scene-lift', `${((.5 - progress) * 18).toFixed(1)}px`); }); }
  window.addEventListener('scroll', updateScenes, { passive: true }); updateScenes();
  function initNetworkCanvas() {
    const canvas = document.querySelector('#network-canvas');
    if (!canvas || root.classList.contains('reduce-motion') || matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const context = canvas.getContext('2d'); if (!context) { if (fxStatus) fxStatus.querySelector('span').textContent = 'NEXULVI FX // CSS FALLBACK'; return; }
    const hero = canvas.closest('.hero'); let width = 0; let height = 0; let particles = []; let mouseX = 0; let mouseY = 0; let scrollEnergy = 0; let lastScroll = window.scrollY;
    function resize() { const bounds = hero.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); width = bounds.width; height = bounds.height; canvas.width = width * dpr; canvas.height = height * dpr; context.setTransform(dpr, 0, 0, dpr, 0, 0); const isTouch = matchMedia('(hover: none)').matches; const count = Math.max(isTouch ? 45 : 85, Math.min(isTouch ? 90 : 190, Math.floor(width * height / (isTouch ? 14000 : 7600)))); particles = Array.from({ length: count }, () => ({ x: Math.random() * width, y: Math.random() * height, z: .25 + Math.random() * .9, vx: (Math.random() - .5) * .18, vy: (Math.random() - .5) * .18, size: .5 + Math.random() * 1.8, phase: Math.random() * Math.PI * 2 })); }
    function draw(time) { context.clearRect(0, 0, width, height); const centerX = width * .66 + mouseX * 55; const centerY = height * .48 + mouseY * 35; const localEnergy = Math.min(scrollEnergy, 1); particles.forEach((particle) => { particle.x += particle.vx * (1 + localEnergy * 5); particle.y += particle.vy * (1 + localEnergy * 5); if (particle.x < -20) particle.x = width + 20; if (particle.x > width + 20) particle.x = -20; if (particle.y < -20) particle.y = height + 20; if (particle.y > height + 20) particle.y = -20; const dx = particle.x - centerX; const dy = particle.y - centerY; const distance = Math.sqrt(dx * dx + dy * dy); if (distance < 170) { particle.x += dx / distance * .32; particle.y += dy / distance * .32; } const alpha = Math.max(.08, .55 - distance / 850) * particle.z; context.beginPath(); context.fillStyle = `rgba(141,255,224,${alpha})`; context.arc(particle.x + mouseX * particle.z * 20, particle.y + mouseY * particle.z * 14, particle.size * particle.z, 0, Math.PI * 2); context.fill(); });
      for (let i = 0; i < particles.length; i += 1) for (let j = i + 1; j < particles.length; j += 1) { const a = particles[i]; const b = particles[j]; const dx = a.x - b.x; const dy = a.y - b.y; const distance = Math.sqrt(dx * dx + dy * dy); if (distance < 108) { context.beginPath(); context.strokeStyle = `rgba(141,255,224,${(1 - distance / 108) * .23})`; context.lineWidth = .55; context.moveTo(a.x, a.y); context.lineTo(b.x, b.y); context.stroke(); } }
      const pulse = 38 + Math.sin(time * .002) * 8 + localEnergy * 22; const glow = context.createRadialGradient(centerX, centerY, 0, centerX, centerY, pulse * 3); glow.addColorStop(0, 'rgba(141,255,224,.28)'); glow.addColorStop(.35, 'rgba(153,133,255,.1)'); glow.addColorStop(1, 'rgba(141,255,224,0)'); context.fillStyle = glow; context.beginPath(); context.arc(centerX, centerY, pulse * 3, 0, Math.PI * 2); context.fill(); scrollEnergy *= .93; window.requestAnimationFrame(draw); }
    window.addEventListener('resize', resize); window.addEventListener('pointermove', (event) => { const rect = hero.getBoundingClientRect(); mouseX = (event.clientX - rect.left - rect.width / 2) / rect.width; mouseY = (event.clientY - rect.top - rect.height / 2) / rect.height; }, { passive: true }); window.addEventListener('scroll', () => { scrollEnergy = Math.min(1, Math.abs(window.scrollY - lastScroll) / 35); lastScroll = window.scrollY; }, { passive: true }); resize(); if (fxStatus) fxStatus.querySelector('span').textContent = 'NEXULVI FX // CANVAS + S3D'; window.requestAnimationFrame(draw);
  }
  initNetworkCanvas();
})();
